[package]
name = "unblocker"
version = "0.1.0"
edition = "2021"

[dependencies]
rprompt = "2.1.1"
toml = "0.8.19"
tokio = "1.41.0"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.132"
winapi = { version = "0.3.9", features = ["winuser", "wincon"] }
